# Add mlflow server to docker-compose.yml

services:
  mlflow-server:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      MLFLOW_TRACKING_USERNAME: admin
      MLFLOW_TRACKING_PASSWORD: admin